### ISSUE TITLE
Hi stephband, 

### ISSUE THREAD

**Issue by abhishekbhalani** [stephband/sequencer.js#1]
How can I use the sequencer file to test it.?
in which type of project I can use? please explain me about this file and project.

can you give me sample demo in brief.?

**Comment by stephband** [comment]
Hi.

This really is a brand new project, and I haven't had chance to write any
docs.

It's not ready for testing. At the moment it's tested only in node (using
the test.js file), not in the browser, although it should run in both.

It will change. If you want to help out, I'd welcome that.

**Comment by stephband** [comment]
I've written a better README which should explan what it does so far... https://github.com/stephband/sequencer.js

**Comment by abhishekbhalani** [comment]
Thanks stephband.
